### ISSUE TITLE
Possibility of including generated header files in unit tests?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/daq-cmake#13]
I would like to make use of the code that has been generated in the Structs.hpp and Nljs.hpp files in the unit tests for the same package.**

However, simply including dfmodules/hdf5datastore/Structs.hpp in a unit test source code file does not work.  My sense is that the /src subdirectory is not being added to the INCLUDE PATH for unit tests.  This theory seems to be confirmed when I look in the daq-cmake code; it seems like the /src subdirectory is only being added to the INCLUDE PATH  for plugins.  

Thinking about this a little bit, it seems like there are at least a couple of options:

1. the /src subdir could be added to the INCLUDE PATH for unit tests (and maybe all types of source code in a package)
2. we could generate the header files that will be used in unit tests and in other "external" code into directories that live underneath /include.  (This would imply that we are considering these header files as PUBLIC, which would be fine with me.)  If we go this route, I'd find it helpful to understand how to specify the generation output directory.

** In unit tests, I would find it very helpful to be able to create an instance of one of the configuration Structs (that are defined in Structs.hpp files) and get all of the default parameter values automatically.  Then, I could simply tweak the few that I want to change for the unit test.  I would also like the ability to use the functions defined in the Nljs.hpp file.  For example, I would like to create an HDF5DataStore configuration Struct (object) in a unit test and convert it to JSON using a function from the corresponding Nljs.hpp file.  With that JSON, I could dynamically create an HDF5DataStore plugin in a similar way that we do in our DAQModules.

**Comment by alessandrothea** [comment]
Hi Kurt,

Thanks for bringing this up. This was an oversight, as the generated code should be clearly accessible to unit tests.
@jcfreeman2 can you add `src` to the unit test include paths in `daq_add_unit_test`? Thanks.
Alessandro

**Comment by jcfreeman2** [comment]
OK, I've update `DAQ.cmake`. Since to obtain the bugfix developers need to explicitly check out and build the daq-cmake repo rather than relying on the installed dunedaq-v2.0.0 package, I updated the instructions at https://github.com/DUNE-DAQ/minidaqapp/wiki/Simple-instructions-for-running-the-app

**Comment by bieryAtFnal** [comment]
Thanks, John, this is great.  
And, a special thanks for updating the Wiki page.

**Comment by alessandrothea** [comment]
This can be closed, right?

**Comment by jcfreeman2** [comment]
Handled through PR 14
