### ISSUE TITLE
Add (optional) optimization flags

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/daq-cmake#16]
If I'm reading correctly, the `daq-cmake` build is currently done with no optimization flags set. That's fine for a lot of the tests we're doing, but we will sometimes want performance tests, where optimization flags are needed (eg, we have some in the MiniDAQApp).  

(As a workaround, I've just been manually adding `-O2` to the flags in `DAQ.cmake`)

**Comment by alessandrothea** [comment]
Thanks for reporting this @philiprodrigues . Both optimised and debug build mode will be needed, so I suggest to add a flag to switch between the two (with the optimization flags turned on by default)
