### ISSUE TITLE
Schema from `test/schema` need to be available to python configs

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/daq-cmake#32]
Eric noticed that schema files in `test/schema` are not available to python configs. It looks to me like the contents of `schema/` are installed/copied-to-build-dir by daq-cmake, but the contents of `test/schema` are not. I think the moo model path in `dunedaq.env` will also need to be updated.

**Comment by alessandrothea** [comment]
Well spotted. I'll add it and make a PR.
