### ISSUE TITLE
codegen dir not included in target_include_directories of "interface"-style main library

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/daq-cmake#35]
When the main library created by `daq_add_library()` is an interface library (ie, one with no srcs), the codegen dir is not included in `target_include_directories`, here:

https://github.com/DUNE-DAQ/daq-cmake/blob/d5f7e63ccbf5633cd3f62f517b9033d2764c75ca/cmake/DAQ.cmake#L349

This means that downstream packages can't find the codegen headers if this package. The issue is showing up for me in my attempt to convert the `serialization` package to use `daq_codegen`

**Comment by alessandrothea** [comment]
Thanks for caching this, fix in progress.
