### ISSUE TITLE
moo dependencies regenerated on every run

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/daq-cmake#39]
`daq-cmake` rebuilds moo dependencies on every run, even when nothing has changed:

```
> cmake --build build >/dev/null && cmake --build build # Second build should have nothing to do
[0/2] Re-checking globbed directories...
[150/150] Updating moo dependencies of /nfs/sw/work_dirs/phrodrig/dunedaq-2.3.0-testrels/minidaqapp-2021-03-09/sourcecode/readout/schema/readout/fakecardreader.jsonnet
```
On a slow machine, and/or with a working area containing many packages, this can take a long time

https://github.com/brettviren/moo/pull/26 adds a `render-deps` command to moo which can be used to produce a `.d` file to pass to the `DEPFILE` option of CMake's `add_custom_command()` to avoid any unnecessary work.

**Comment by alessandrothea** [comment]
Thanks Phil. Looks very nice. A couple of questions:
- Did I understand correctly that cmake 3.20 is required to be able to use `.d` files?
- This new moo feature reduces the number of moo calls to check dependencies, but doesn't the dependency file have to be updated every time, doesn't it? I believe that this is what happens with gcc-generated `.d` files as well. Or am I missing something?

**Comment by philiprodrigues** [comment]
Cmake 3.20 is needed to use `.d` files with the Makefile backend, but it works with 3.17 and the ninja backend.

The dependency file itself doesn't need to be updated when nothing has changed: make/ninja reads the dependency file (to get the "indirect" dependencies) in addition to knowing the direct dependencies, so it can know that the actual target (`Structs.hpp` or whatever) is newer than all of its inputs _and_ newer than the dependency file. In that case, nothing needs to be rebuilt.

Eg if `Structs.hpp` is produced from `mymodel.jsonnet` and `mytemplate.hpp.j2`, and additionally, `mymodel.jsonnet` imports `myimport.jsonnet`, then from the combination of `Structs.hpp.d` and the dependencies directly given to `add_custom_command()`, make/ninja knows that `Structs.hpp` depends on `mymodel.jsonnet`, `mytemplate.hpp.j2` and `myimport.jsonnet`.

If any of those three inputs have changed, then `Structs.hpp` needs to be rebuilt, which also must trigger a rebuild of `Structs.hpp.d`. (In the `daq-cmake` case, that means that the `add_custom_command` that calls `moo render` _must_ also call `moo render-deps`)

**Comment by alessandrothea** [comment]
Ha! Indeed, now I get it, thanks. The dependencies are generated in the same cmake custom command as `render`.
I think I could have done that with `imports`.
Good, so shall we try to sneak this in the release next week?

**Comment by philiprodrigues** [comment]
Sounds good to me, if @brettviren is happy to make a moo release. Example of how it could be used in `daq-cmake` at:

https://github.com/philiprodrigues/daq-cmake

**Comment by brettviren** [comment]
Any time.

https://github.com/brettviren/moo/releases/tag/0.5.6

**Comment by alessandrothea** [comment]
Thanks @brettviren @philiprodrigues , I'll have a look
