### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by strilov** [DUNE-DAQ/daq-cmake#46]
In order to support the calling of C++ code from python within the DUNE DAQ environment, a new DUNE DAQ CMake function, `daq_add_python_library`, has been introduced. The function compiles the C++ source files, which expose the desired functions, classes, etc., and creates a `.so` file, which can be imported in python. The binding of the C++ code to python is done using the header only library, `pybind11` (available as a package under the DUNE DAQ `externals` category).
The function currently expects the sourcecode/python module hierarchy described below. This convention was chosen to allow a first implementation of a mechanism for binding of C++ code to python in the DUNE DAQ software environment. The convention can and should evolve as requirements change or improvements are suggested.

* The DUNE package implements an eponymous top level python module, i.e. `python/${PACKAGE_NAME}`. 
* C++ code is exposed with `pybind11` via one top python module which is to be called `_daq_${PACKAGE_NAME}_py`. 
* The C++ python wrapper code is to be found in the newly introduced `pysrc` package directory.
* Once the wrapper source code is compiled, the resulting `_daq_${PACKAGE_NAME}_py.so` file will be placed in the directory of the top level package python module. 
* The top level package python module can import the desired components from `_daq_${PACKAGE_NAME}_py` via its `__init__.py`. 
* Optionally, C++ code can be exposed via sub-modules of the `_daq_${PACKAGE_NAME}_py` module, and imported with corresponding `__init__.py` files placed sub-directories of the top level package python mdoule.

A working example of this can be found in the `toylibrary` package within the repository, on branch: https://github.com/DUNE-DAQ/daq-cmake/tree/feature/python_bindings. For convenience, the structure of the `sourcecode` and `build` toylibrary directories relevant to the python binding are reproduced below. 

```
sourcecode
└── toylibrary
    ├── pysrc
    │   └── toy_wrapper.cpp
    ├── python
    │   └── toylibrary
    │       ├── __init__.py
    │       ├── play
    │       │   └── __init__.py
    │       └── wind
    │           └── __init__.py
    └── scripts
        └── toyscript.py
```

```
build
└── toylibrary
    ├── python
    │   └── toylibrary
    │       ├── _daq_toylibrary_py.so
    │       ├── __init__.py
    │       ├── play
    │       │   └── __init__.py
    │       └── wind
    │           └── __init__.py
    └── scripts
        └── toyscript.py
```
The python script `toyscript.py` demonstrates how the top level python package and its exposed C++ components can be imported and used.

The `timing` package has also made use of this prototype python binding mechanism. See this branch: https://github.com/DUNE-DAQ/timing/tree/feature/cmake_python_bindings.

Any comments and suggestions are welcome.

**Comment by alessandrothea** [comment]
Thanks for filing the issue and preparing the prototype.
Both the implementation and the example look very good to me.
I think there are only few very minor details to be tweaked before merging to master and including it into the next release:
- the cmake function: I would use the word `bindings` in the function name, to make explicit that it's supposed to be used for bindings only (at this stage at least): `daq_add_python_bindings`
- same for the source folder name: how about `pybindsrc`? 
- we discussed about allowing to move the generated library in a subdirectory of `python/${PACKAGE}` to support cases like the timing package, where the bindings library is currently installed in `python/timing/core/`

@jcfreeman2 @dingp Do you have any comments/feedback?

**Comment by strilov** [comment]
Hi Alessandro,

The first two points seem OK to me.

As for the third one, placing the `.so` file under the sub-module directory would imply that C++ code was only exposed via the submodule, and nothing was exposed via the top level module, or other modules. I think the 'from .. import` scheme is flexible enough to support sub-modules, with the `.so` living in the top level module directory.

**Comment by alessandrothea** [comment]
Alright, I would have left the choice to the package developer.
So, if we don't grant such freedom, can you give an example of how it would work for the `timing` package, in terms of imports et all?

**Comment by jcfreeman2** [comment]
@strilov I think that modulo the details that you and Alessandro are working out, this looks very useful. The one thing I'd add is that when there's a feature branch which changes a package's functionality, its documentation on that feature branch should be changed accordingly as well. So it would be great if, before we merge your changes into daq-cmake's develop branch, you did the following:
* Cut-and-paste the very nice description of `daq_add_python_library` you have in the `DAQ.cmake` source into the "Description of the CMake functions provided by daq-cmake" section of `docs/README.md`
* Update the description of the toylibrary to reflect how you added to it

General instructions on the technical aspects of how to update a package's documentation can be found in https://dune-daq-sw.readthedocs.io/en/latest/editing_package_documentation/.

**Comment by jcfreeman2** [comment]
Also: I merged `develop` into `feature/python_bindings` a moment ago so it would pick up a recent change I made to the daq-cmake documentation unrelated to this new function; this will prevent any potential clashes between the documentation on the two branches, since I won't be touching it for a while.

**Comment by strilov** [comment]
@alessandrothea So if we wanted to have `.so` live somewhere other than the top level package, I think we'd add something like an `SUBMODULE` option to `daq_add_python_library`. If that option is specified, then the `.so` file would be placed in python/${PACKAGE_NAME}/${LIBOPTS_SUBMODULE}.

So if that option was used for the `timing.core` module, then `python/timing/core/__init__.py` would go from
`from .._daq_timing_py.core import *`
to 
`from ._daq_timing_py.core import *`.
 another variable to the cmake function which specifies where the `.so` should end up.

For example

**Comment by strilov** [comment]
In this case, one could also expose everything through the top level module. In such a case, `python/timing/core/__init__.py` could be just:
`from ._daq_timing_py import *`

**Comment by alessandrothea** [comment]
Understood. I was more interested in how the current implementation applies to timing:

- `_daq_timing_py` is placed in `python/timing`
- `python/timing/core/__init__.py` contains the line `from .._daq_timing_py.core import *`
   * This allows to `import timing.core`?
- What do you expect to be the content of `python/timing/__init__.py` Should it contain something like `from . _daq_timing_py import *`. I agree, this question doesn't fit well with the timing package structure, by hypothetically?

**Comment by strilov** [comment]
Ah OK, sorry. Yes, the first two points are exactly right. 

With regards to the top level, `python/timing/__init__.py`, since it doesn't need anything from `_daq_timing_py`, it just has the line: `import uhal`.

**Comment by alessandrothea** [comment]
OK, I've just realised that the answer to my question (what happens in the current paradigm with multiple submodules) is in your branch 🤦 .
Very good. I'm happy with the current implementation then. How about fixing the names (`daq_add_python_bindings` and `pybindsrc`) and going for a PR?

**Comment by strilov** [comment]
OK. The migration to pybindsrc and daq_add_python_binding_library and the documentation are in. PR here: https://github.com/DUNE-DAQ/daq-cmake/pull/47
