### ISSUE TITLE
Compilation error with software area that has dataformats but not dfmessages

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/daq-cmake#57]
When I run the instructions on [this page](https://github.com/DUNE-DAQ/minidaqapp/wiki/Staging-page-for-v2.8.0-setup-instructions) (which I will try to copy into this Issue), I get a  compiler error along the lines of the following, when I run `dbt-build.sh`:
```
CMake Error in dfmodules/CMakeLists.txt:
  Imported target "dfmessages::dfmessages" includes non-existent path

    "/home/biery/dunedaq/22Jun/build/dataformats/codegen/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

When I add the _dfmessages_ package to my software area, the build error goes away.

Is this expected?  Is there a reason why I need to include the _dfmessages_ package in my software area?
Thanks,
Kurt

**Comment by alessandrothea** [comment]
Hi Kurt,

In my understanding, this issue is the result of a fragility of cmake. It doesn't cope well with compiling certain mixtures of compiled and local packages. Specifically, given packages `A`, `B` and `C`, where `A` depends on `B` and `B` on `C`, if `A` and `C` are being compiled from source, `B` needs to be compiled as well. In your case `B` is `dfmessages`

**Comment by bieryAtFnal** [comment]
OK, thanks.
In the short term, I have added _dfmessages_ to the list of packages to include in a new v2.8 software area, partly for this reason and partly because of changes in that package.

However, I see that John made a code change that he describes in PR #58.  When I remove _dfmessages_ from the software area and use John's _daq-cmake_ branch, I also see the software area successfully compile.
