### ISSUE TITLE
Install scripts subdirectory of a package

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/daq-cmake#8]
It would be good if the `scripts` subdirectory of a package can be installed in the package's install area, as well as the `schema` subdirectory, or any other subdirectories with files required when running its application.

This will eliminate the need of local clones, for example, running the `restcmd` in `dunedaq-v2.0.0` release.

**Comment by jcfreeman2** [comment]
In that case, one thing to think about will be: is it OK for jsonnet/json files which get installed to refer to plugins which don't get installed? To take a specific example, there are json files in appfwk's `schema` subdirectory which use the not-installed FakeDataProducerDAQModule and FakeDataConsumerDAQModule.

**Comment by alessandrothea** [comment]
Solved in #11.
Closing.
