### ISSUE TITLE
Support for ProtoBuf schemas

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/daq-cmake#83]
in order to Complete https://github.com/DUNE-DAQ/daq-deliverables/issues/85 we need to support schema creation using ProtoBuf.

**Comment by jcfreeman2** [comment]
I just spoke with Marco; here's a bit of context:
* Like with `moo`, we want to call protobuf's `protoc` to generate C++ code off a template file 
* _Unlike_ `moo`, this generated code is not header-only - along with generating a `*.h` file it includes a generated `*.cc` file
* Also we'll generate Python code, though this'll be easy to handle
* This generated code won't necessarily be local to the package. E.g., protobuf-generated code in ers will be used by erskafka

In light of this, one approach we could take is to have a CMake function like `daq_protobuf()` which will look in the `schema/<packagename>` directory for a file with the `*.proto` extension, and generate C++/Python code off it. Then this code could be automatically added to the build of the package-wide library. Thus if the developer doesn't also call the CMake function `daq_add_library` the build will fail and the developer will be informed as to the protobuf-related reason.
