### ISSUE TITLE
Changes to how daq-cmake handles OKS

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/daq-cmake#90]
Alessandro wants the following:
* That the source files produced from OKS get compiled into the package-wide shared object library, and not a separate shared object library
* That the `daq_oks_codegen` function be moved from genconfig into this package
* (Ideally) that it be possible to add a class to an OKS schema file without needing to perform a `--clean` build to properly incorporate it

**Comment by gcrone** [comment]
Hi,
  I've only just seen this issue.  I think we discussed the option of putting the generated dal code into the primary library of the package some time ago and decided against it. The argument against is that code that is just parsing the configuration for some module doesn't want to have to load the whole implementation code of the module and all its dependent libraries.

**Comment by jcfreeman2** [comment]
Right, we discussed this at a meeting back in May but Alessandro wasn't present. However, he's made it clear that he wants the code to be in the primary library.

**Comment by jcfreeman2** [comment]
Handled via PR #96
